// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WidevinePSSH.proto

package org.cablelabs.widevine.proto;

public final class WidevinePSSHProtoBuf {
  private WidevinePSSHProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WidevineCencHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .WidevineCencHeader.Algorithm algorithm = 1;
    /**
     * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
     */
    boolean hasAlgorithm();
    /**
     * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
     */
    org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.Algorithm getAlgorithm();

    // repeated bytes key_id = 2;
    /**
     * <code>repeated bytes key_id = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getKeyIdList();
    /**
     * <code>repeated bytes key_id = 2;</code>
     */
    int getKeyIdCount();
    /**
     * <code>repeated bytes key_id = 2;</code>
     */
    com.google.protobuf.ByteString getKeyId(int index);

    // optional string provider = 3;
    /**
     * <code>optional string provider = 3;</code>
     *
     * <pre>
     * Content provider name. 
     * </pre>
     */
    boolean hasProvider();
    /**
     * <code>optional string provider = 3;</code>
     *
     * <pre>
     * Content provider name. 
     * </pre>
     */
    java.lang.String getProvider();
    /**
     * <code>optional string provider = 3;</code>
     *
     * <pre>
     * Content provider name. 
     * </pre>
     */
    com.google.protobuf.ByteString
        getProviderBytes();

    // optional bytes content_id = 4;
    /**
     * <code>optional bytes content_id = 4;</code>
     *
     * <pre>
     * A content identifier, specified by content provider. 
     * </pre>
     */
    boolean hasContentId();
    /**
     * <code>optional bytes content_id = 4;</code>
     *
     * <pre>
     * A content identifier, specified by content provider. 
     * </pre>
     */
    com.google.protobuf.ByteString getContentId();

    // optional string track_type = 5;
    /**
     * <code>optional string track_type = 5;</code>
     *
     * <pre>
     * Track type. Acceptable values are SD, HD and AUDIO. Used to differentiate 
     * content keys used by an asset. 
     * </pre>
     */
    boolean hasTrackType();
    /**
     * <code>optional string track_type = 5;</code>
     *
     * <pre>
     * Track type. Acceptable values are SD, HD and AUDIO. Used to differentiate 
     * content keys used by an asset. 
     * </pre>
     */
    java.lang.String getTrackType();
    /**
     * <code>optional string track_type = 5;</code>
     *
     * <pre>
     * Track type. Acceptable values are SD, HD and AUDIO. Used to differentiate 
     * content keys used by an asset. 
     * </pre>
     */
    com.google.protobuf.ByteString
        getTrackTypeBytes();

    // optional string policy = 6;
    /**
     * <code>optional string policy = 6;</code>
     *
     * <pre>
     * The name of a registered policy to be used for this asset. 
     * </pre>
     */
    boolean hasPolicy();
    /**
     * <code>optional string policy = 6;</code>
     *
     * <pre>
     * The name of a registered policy to be used for this asset. 
     * </pre>
     */
    java.lang.String getPolicy();
    /**
     * <code>optional string policy = 6;</code>
     *
     * <pre>
     * The name of a registered policy to be used for this asset. 
     * </pre>
     */
    com.google.protobuf.ByteString
        getPolicyBytes();
  }
  /**
   * Protobuf type {@code WidevineCencHeader}
   */
  public static final class WidevineCencHeader extends
      com.google.protobuf.GeneratedMessage
      implements WidevineCencHeaderOrBuilder {
    // Use WidevineCencHeader.newBuilder() to construct.
    private WidevineCencHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WidevineCencHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WidevineCencHeader defaultInstance;
    public static WidevineCencHeader getDefaultInstance() {
      return defaultInstance;
    }

    public WidevineCencHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WidevineCencHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.Algorithm value = org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.Algorithm.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                algorithm_ = value;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                keyId_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              keyId_.add(input.readBytes());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              provider_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              contentId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              trackType_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              policy_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          keyId_ = java.util.Collections.unmodifiableList(keyId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.internal_static_WidevineCencHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.internal_static_WidevineCencHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.class, org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<WidevineCencHeader> PARSER =
        new com.google.protobuf.AbstractParser<WidevineCencHeader>() {
      public WidevineCencHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WidevineCencHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WidevineCencHeader> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code WidevineCencHeader.Algorithm}
     */
    public enum Algorithm
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNENCRYPTED = 0;</code>
       */
      UNENCRYPTED(0, 0),
      /**
       * <code>AESCTR = 1;</code>
       */
      AESCTR(1, 1),
      ;

      /**
       * <code>UNENCRYPTED = 0;</code>
       */
      public static final int UNENCRYPTED_VALUE = 0;
      /**
       * <code>AESCTR = 1;</code>
       */
      public static final int AESCTR_VALUE = 1;


      public final int getNumber() { return value; }

      public static Algorithm valueOf(int value) {
        switch (value) {
          case 0: return UNENCRYPTED;
          case 1: return AESCTR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Algorithm>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Algorithm>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Algorithm>() {
              public Algorithm findValueByNumber(int number) {
                return Algorithm.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.getDescriptor().getEnumTypes().get(0);
      }

      private static final Algorithm[] VALUES = values();

      public static Algorithm valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Algorithm(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:WidevineCencHeader.Algorithm)
    }

    private int bitField0_;
    // optional .WidevineCencHeader.Algorithm algorithm = 1;
    public static final int ALGORITHM_FIELD_NUMBER = 1;
    private org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.Algorithm algorithm_;
    /**
     * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
     */
    public boolean hasAlgorithm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
     */
    public org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.Algorithm getAlgorithm() {
      return algorithm_;
    }

    // repeated bytes key_id = 2;
    public static final int KEY_ID_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> keyId_;
    /**
     * <code>repeated bytes key_id = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getKeyIdList() {
      return keyId_;
    }
    /**
     * <code>repeated bytes key_id = 2;</code>
     */
    public int getKeyIdCount() {
      return keyId_.size();
    }
    /**
     * <code>repeated bytes key_id = 2;</code>
     */
    public com.google.protobuf.ByteString getKeyId(int index) {
      return keyId_.get(index);
    }

    // optional string provider = 3;
    public static final int PROVIDER_FIELD_NUMBER = 3;
    private java.lang.Object provider_;
    /**
     * <code>optional string provider = 3;</code>
     *
     * <pre>
     * Content provider name. 
     * </pre>
     */
    public boolean hasProvider() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string provider = 3;</code>
     *
     * <pre>
     * Content provider name. 
     * </pre>
     */
    public java.lang.String getProvider() {
      java.lang.Object ref = provider_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          provider_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string provider = 3;</code>
     *
     * <pre>
     * Content provider name. 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getProviderBytes() {
      java.lang.Object ref = provider_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        provider_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes content_id = 4;
    public static final int CONTENT_ID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString contentId_;
    /**
     * <code>optional bytes content_id = 4;</code>
     *
     * <pre>
     * A content identifier, specified by content provider. 
     * </pre>
     */
    public boolean hasContentId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes content_id = 4;</code>
     *
     * <pre>
     * A content identifier, specified by content provider. 
     * </pre>
     */
    public com.google.protobuf.ByteString getContentId() {
      return contentId_;
    }

    // optional string track_type = 5;
    public static final int TRACK_TYPE_FIELD_NUMBER = 5;
    private java.lang.Object trackType_;
    /**
     * <code>optional string track_type = 5;</code>
     *
     * <pre>
     * Track type. Acceptable values are SD, HD and AUDIO. Used to differentiate 
     * content keys used by an asset. 
     * </pre>
     */
    public boolean hasTrackType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string track_type = 5;</code>
     *
     * <pre>
     * Track type. Acceptable values are SD, HD and AUDIO. Used to differentiate 
     * content keys used by an asset. 
     * </pre>
     */
    public java.lang.String getTrackType() {
      java.lang.Object ref = trackType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          trackType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string track_type = 5;</code>
     *
     * <pre>
     * Track type. Acceptable values are SD, HD and AUDIO. Used to differentiate 
     * content keys used by an asset. 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTrackTypeBytes() {
      java.lang.Object ref = trackType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trackType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string policy = 6;
    public static final int POLICY_FIELD_NUMBER = 6;
    private java.lang.Object policy_;
    /**
     * <code>optional string policy = 6;</code>
     *
     * <pre>
     * The name of a registered policy to be used for this asset. 
     * </pre>
     */
    public boolean hasPolicy() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string policy = 6;</code>
     *
     * <pre>
     * The name of a registered policy to be used for this asset. 
     * </pre>
     */
    public java.lang.String getPolicy() {
      java.lang.Object ref = policy_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          policy_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string policy = 6;</code>
     *
     * <pre>
     * The name of a registered policy to be used for this asset. 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPolicyBytes() {
      java.lang.Object ref = policy_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        policy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      algorithm_ = org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.Algorithm.UNENCRYPTED;
      keyId_ = java.util.Collections.emptyList();
      provider_ = "";
      contentId_ = com.google.protobuf.ByteString.EMPTY;
      trackType_ = "";
      policy_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, algorithm_.getNumber());
      }
      for (int i = 0; i < keyId_.size(); i++) {
        output.writeBytes(2, keyId_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getProviderBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, contentId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getTrackTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getPolicyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, algorithm_.getNumber());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < keyId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(keyId_.get(i));
        }
        size += dataSize;
        size += 1 * getKeyIdList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getProviderBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, contentId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getTrackTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPolicyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WidevineCencHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.internal_static_WidevineCencHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.internal_static_WidevineCencHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.class, org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.Builder.class);
      }

      // Construct using org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        algorithm_ = org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.Algorithm.UNENCRYPTED;
        bitField0_ = (bitField0_ & ~0x00000001);
        keyId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        provider_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        contentId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        trackType_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        policy_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.internal_static_WidevineCencHeader_descriptor;
      }

      public org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader getDefaultInstanceForType() {
        return org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.getDefaultInstance();
      }

      public org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader build() {
        org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader buildPartial() {
        org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader result = new org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.algorithm_ = algorithm_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          keyId_ = java.util.Collections.unmodifiableList(keyId_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.keyId_ = keyId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.provider_ = provider_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.contentId_ = contentId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.trackType_ = trackType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.policy_ = policy_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader) {
          return mergeFrom((org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader other) {
        if (other == org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.getDefaultInstance()) return this;
        if (other.hasAlgorithm()) {
          setAlgorithm(other.getAlgorithm());
        }
        if (!other.keyId_.isEmpty()) {
          if (keyId_.isEmpty()) {
            keyId_ = other.keyId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureKeyIdIsMutable();
            keyId_.addAll(other.keyId_);
          }
          onChanged();
        }
        if (other.hasProvider()) {
          bitField0_ |= 0x00000004;
          provider_ = other.provider_;
          onChanged();
        }
        if (other.hasContentId()) {
          setContentId(other.getContentId());
        }
        if (other.hasTrackType()) {
          bitField0_ |= 0x00000010;
          trackType_ = other.trackType_;
          onChanged();
        }
        if (other.hasPolicy()) {
          bitField0_ |= 0x00000020;
          policy_ = other.policy_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .WidevineCencHeader.Algorithm algorithm = 1;
      private org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.Algorithm algorithm_ = org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.Algorithm.UNENCRYPTED;
      /**
       * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
       */
      public boolean hasAlgorithm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
       */
      public org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.Algorithm getAlgorithm() {
        return algorithm_;
      }
      /**
       * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
       */
      public Builder setAlgorithm(org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.Algorithm value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        algorithm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
       */
      public Builder clearAlgorithm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        algorithm_ = org.cablelabs.widevine.proto.WidevinePSSHProtoBuf.WidevineCencHeader.Algorithm.UNENCRYPTED;
        onChanged();
        return this;
      }

      // repeated bytes key_id = 2;
      private java.util.List<com.google.protobuf.ByteString> keyId_ = java.util.Collections.emptyList();
      private void ensureKeyIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          keyId_ = new java.util.ArrayList<com.google.protobuf.ByteString>(keyId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes key_id = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getKeyIdList() {
        return java.util.Collections.unmodifiableList(keyId_);
      }
      /**
       * <code>repeated bytes key_id = 2;</code>
       */
      public int getKeyIdCount() {
        return keyId_.size();
      }
      /**
       * <code>repeated bytes key_id = 2;</code>
       */
      public com.google.protobuf.ByteString getKeyId(int index) {
        return keyId_.get(index);
      }
      /**
       * <code>repeated bytes key_id = 2;</code>
       */
      public Builder setKeyId(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeyIdIsMutable();
        keyId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes key_id = 2;</code>
       */
      public Builder addKeyId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeyIdIsMutable();
        keyId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes key_id = 2;</code>
       */
      public Builder addAllKeyId(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureKeyIdIsMutable();
        super.addAll(values, keyId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes key_id = 2;</code>
       */
      public Builder clearKeyId() {
        keyId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // optional string provider = 3;
      private java.lang.Object provider_ = "";
      /**
       * <code>optional string provider = 3;</code>
       *
       * <pre>
       * Content provider name. 
       * </pre>
       */
      public boolean hasProvider() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string provider = 3;</code>
       *
       * <pre>
       * Content provider name. 
       * </pre>
       */
      public java.lang.String getProvider() {
        java.lang.Object ref = provider_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          provider_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string provider = 3;</code>
       *
       * <pre>
       * Content provider name. 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getProviderBytes() {
        java.lang.Object ref = provider_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          provider_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string provider = 3;</code>
       *
       * <pre>
       * Content provider name. 
       * </pre>
       */
      public Builder setProvider(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        provider_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string provider = 3;</code>
       *
       * <pre>
       * Content provider name. 
       * </pre>
       */
      public Builder clearProvider() {
        bitField0_ = (bitField0_ & ~0x00000004);
        provider_ = getDefaultInstance().getProvider();
        onChanged();
        return this;
      }
      /**
       * <code>optional string provider = 3;</code>
       *
       * <pre>
       * Content provider name. 
       * </pre>
       */
      public Builder setProviderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        provider_ = value;
        onChanged();
        return this;
      }

      // optional bytes content_id = 4;
      private com.google.protobuf.ByteString contentId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content_id = 4;</code>
       *
       * <pre>
       * A content identifier, specified by content provider. 
       * </pre>
       */
      public boolean hasContentId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes content_id = 4;</code>
       *
       * <pre>
       * A content identifier, specified by content provider. 
       * </pre>
       */
      public com.google.protobuf.ByteString getContentId() {
        return contentId_;
      }
      /**
       * <code>optional bytes content_id = 4;</code>
       *
       * <pre>
       * A content identifier, specified by content provider. 
       * </pre>
       */
      public Builder setContentId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        contentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content_id = 4;</code>
       *
       * <pre>
       * A content identifier, specified by content provider. 
       * </pre>
       */
      public Builder clearContentId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        contentId_ = getDefaultInstance().getContentId();
        onChanged();
        return this;
      }

      // optional string track_type = 5;
      private java.lang.Object trackType_ = "";
      /**
       * <code>optional string track_type = 5;</code>
       *
       * <pre>
       * Track type. Acceptable values are SD, HD and AUDIO. Used to differentiate 
       * content keys used by an asset. 
       * </pre>
       */
      public boolean hasTrackType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string track_type = 5;</code>
       *
       * <pre>
       * Track type. Acceptable values are SD, HD and AUDIO. Used to differentiate 
       * content keys used by an asset. 
       * </pre>
       */
      public java.lang.String getTrackType() {
        java.lang.Object ref = trackType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          trackType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string track_type = 5;</code>
       *
       * <pre>
       * Track type. Acceptable values are SD, HD and AUDIO. Used to differentiate 
       * content keys used by an asset. 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTrackTypeBytes() {
        java.lang.Object ref = trackType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          trackType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string track_type = 5;</code>
       *
       * <pre>
       * Track type. Acceptable values are SD, HD and AUDIO. Used to differentiate 
       * content keys used by an asset. 
       * </pre>
       */
      public Builder setTrackType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        trackType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string track_type = 5;</code>
       *
       * <pre>
       * Track type. Acceptable values are SD, HD and AUDIO. Used to differentiate 
       * content keys used by an asset. 
       * </pre>
       */
      public Builder clearTrackType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        trackType_ = getDefaultInstance().getTrackType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string track_type = 5;</code>
       *
       * <pre>
       * Track type. Acceptable values are SD, HD and AUDIO. Used to differentiate 
       * content keys used by an asset. 
       * </pre>
       */
      public Builder setTrackTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        trackType_ = value;
        onChanged();
        return this;
      }

      // optional string policy = 6;
      private java.lang.Object policy_ = "";
      /**
       * <code>optional string policy = 6;</code>
       *
       * <pre>
       * The name of a registered policy to be used for this asset. 
       * </pre>
       */
      public boolean hasPolicy() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string policy = 6;</code>
       *
       * <pre>
       * The name of a registered policy to be used for this asset. 
       * </pre>
       */
      public java.lang.String getPolicy() {
        java.lang.Object ref = policy_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          policy_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string policy = 6;</code>
       *
       * <pre>
       * The name of a registered policy to be used for this asset. 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPolicyBytes() {
        java.lang.Object ref = policy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          policy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string policy = 6;</code>
       *
       * <pre>
       * The name of a registered policy to be used for this asset. 
       * </pre>
       */
      public Builder setPolicy(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        policy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string policy = 6;</code>
       *
       * <pre>
       * The name of a registered policy to be used for this asset. 
       * </pre>
       */
      public Builder clearPolicy() {
        bitField0_ = (bitField0_ & ~0x00000020);
        policy_ = getDefaultInstance().getPolicy();
        onChanged();
        return this;
      }
      /**
       * <code>optional string policy = 6;</code>
       *
       * <pre>
       * The name of a registered policy to be used for this asset. 
       * </pre>
       */
      public Builder setPolicyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        policy_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:WidevineCencHeader)
    }

    static {
      defaultInstance = new WidevineCencHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:WidevineCencHeader)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_WidevineCencHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WidevineCencHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022WidevinePSSH.proto\"\312\001\n\022WidevineCencHea" +
      "der\0220\n\talgorithm\030\001 \001(\0162\035.WidevineCencHea" +
      "der.Algorithm\022\016\n\006key_id\030\002 \003(\014\022\020\n\010provide" +
      "r\030\003 \001(\t\022\022\n\ncontent_id\030\004 \001(\014\022\022\n\ntrack_typ" +
      "e\030\005 \001(\t\022\016\n\006policy\030\006 \001(\t\"(\n\tAlgorithm\022\017\n\013" +
      "UNENCRYPTED\020\000\022\n\n\006AESCTR\020\001B4\n\034org.cablela" +
      "bs.widevine.protoB\024WidevinePSSHProtoBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_WidevineCencHeader_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_WidevineCencHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_WidevineCencHeader_descriptor,
              new java.lang.String[] { "Algorithm", "KeyId", "Provider", "ContentId", "TrackType", "Policy", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
